# Generated by Django 2.2.8 on 2020-04-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200416_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='titre_slug',
            field=models.SlugField(editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='titre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
